# # Generated by the vetiver package; edit with care
# start with python base image
FROM python:3.13

# create directory in container for vetiver files
WORKDIR /vetiver

# copy  and install requirements
COPY vetiver_requirements.txt /vetiver/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /vetiver/requirements.txt

# copy app file
COPY app.py /vetiver/app/app.py
COPY service-auth.json /vetiver/app/service-auth.json
ENV GOOGLE_APPLICATION_CREDENTIALS="/vetiver/app/service-auth.json"
# expose port
EXPOSE 2222

# run vetiver API
CMD ["uvicorn", "app.app:api", "--host", "0.0.0.0", "--port", "2222"]
